### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by jdappel** [okcredit/android-cold-startup-instrumentation#1]
The current implementation is only usable from Kotlin not Java

**Comment by anjalsaneen** [comment]
@jdappel 


it's using higher-order functions in kotlin(FunctionN). After converting to java you can use below code in Java Classes.

```
    @Override
    public void onCreate() {
        AppStartUpTracer.INSTANCE.start(); 
        super.onCreate();

        AppStartUpTracer.INSTANCE.stop(this, s -> {
            Log.v("StartUp Logs", s.toString());
            return Unit.INSTANCE;
        });
    }
```


Note: Class Unit belongs to the standard library org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version. so you must have this library as a dependancy. But you don't need Kotlin Android plugin.
