### ISSUE TITLE
Metrics not getting logged when BroadcastReceiver wakes app

### ISSUE THREAD

**Issue by erick-buku** [okcredit/android-cold-startup-instrumentation#3]
I want to measure cold startup time if app is woken from BroadcastReceiver. So steps to reproduce:
- App is in killed state.
- Send intent to my broadcast receiver via adb command: `adb shell am broadcast bla2...`
- Result is success, the app wakes but the metrics are not getting logged like I launch the app from launcher.

Is this expected behavior or am I missing something?

**Comment by anjalsaneen** [comment]
Hi @ericksumargo-buku , Sorry for the delay.

This is expected behavior. Metrics are only returned after the first draw. The App will not draw any frames when it wakes up through BroadcastReceiver.
